- go out
- do something active:
  - go cycling
  - go hiking
  - play a sport:
    - play basketball
    - play football
    - play volleyball
- go to a concert:
  - go to a country concert
  - go to a rock concert
  - go to a folk concert
  - go to a indie concert
  - go to a punk concert
  - go to another concert
- eat something:
  - eat somewhere simple
  - eat somewhere nice
- see a movie: !movie_list
  