# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: eq_dev
  user: <%=ENV["USER"] %>
  password: 
    
test:
  adapter: postgresql
  database: eq_test
  user: <%=ENV["USER"] %>
  password:
    
development:
  adapter: postgresql
  database: eq_production
  user: <%=ENV["USER"] %>
  password: